# Generated by Django 4.2.2 on 2023-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
